### ISSUE TITLE
Another crash at end of trial S60

### ISSUE THREAD

**Issue by c-hospodar** [tqosu/FLEX#15]
I was just framing through to find the next step and the program crashed

Traceback (most recent call last):
  File "/Users/motoruser/Desktop/FLEX-main/FlexUI/app.py", line 948, in setPosition
    self.main3Dviewer.setPosition(position)
  File "/Users/motoruser/Desktop/FLEX-main/FlexUI/ViewerVideo/ResultWidgetApp.py", line 373, in setPosition
    overlay = self.img.copy()
AttributeError: 'ResultApp' object has no attribute 'img'
Abort trap: 6
(myenv) kalab08m:FLEX-main motoruser$ 

2023-12-04_13-42-42_app_log

**Comment by tqosu** [comment]
I didn't reproduce this one but I made some changes that probably will resolve this. Please update the code and reopen this issue again if it still exists.
